'use client'
// import { Inter } from 'next/font/google'
import './globals.css'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import AuthProvider from '@/context/AuthProvider'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { ConfigProvider } from 'antd'
import AntDesignProvider from '@/context/AntdProvider'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// }

export default function RootLayout({ children }) {
  const queryClient = new QueryClient()
  return (

    <AntDesignProvider>
      <QueryClientProvider client={queryClient}>
        <AuthProvider>
          <html lang="en">
            <body>
              {children}
            </body>
          </html>
        </AuthProvider>
        {/* <ReactQueryDevtools initialIsOpen={false} /> */}
      </QueryClientProvider>
    </AntDesignProvider>
  )
}
